### ISSUE TITLE
Annual Accomplishments on Private Landowners page

### ISSUE THREAD

**Issue by jenmstrick** [USFWS/southeast#20]
1. Remove state list from the subnav. Makes it too long IMO.
2. Move "Annual Accomplishments" section to the end so that "Get Started" and "State Coordinators" come earlier on the page. Those are more important in terms of achieving the page's goals.
3. Change subheader anchor tags to be same as subheader text rather than #scrollNav-4, etc.

https://intranet.fws.gov/region4/demo/our-services/private-landowners/partners-program/

**Comment by rhewitt22** [comment]
3 is addressed by #29

**Comment by rhewitt22** [comment]
Closed via #30
