### ISSUE TITLE
Content: add Regional Leadership bios (low priority)

### ISSUE THREAD

**Issue by jenmstrick** [USFWS/southeast#25]
Page will launch with Cindy and Mike's bios only.

Eventually, add bios and photos for all ARDs. https://docs.google.com/a/doi.gov/document/d/1iXdyenaAvve3p-gkIquTkL4GDMdfq9QDCsQaNtKIpBo/edit?usp=sharing

**Comment by rhewitt22** [comment]
Closed via #28
