### ISSUE TITLE
UI: add spyglass to all search bars on site

### ISSUE THREAD

**Issue by jenmstrick** [USFWS/southeast#26]
With text "Search" in the text box just like this. When you click the spyglass, it's like hitting "go."
![screen shot 2016-08-10 at 5 52 58 pm](https://cloud.githubusercontent.com/assets/8572703/17572569/4b47f422-5f23-11e6-9e33-94f7972dc6ec.png)

**Comment by rhewitt22** [comment]
How's this? 

https://codepen.io/rhewitt/full/BzvPOZ/

**Comment by rhewitt22** [comment]
Closed via #31
