### ISSUE TITLE
Yes I'd like Open Sans :)

### ISSUE THREAD

**Issue by jenmstrick** [USFWS/southeast#4]
Body text: Open Sans Light 300, #33333

Bold text and Links: Open Sans Semibold 600

Plenty of line spacing.

**Comment by rhewitt22** [comment]
@jenmstrick I'm not sure Open Sans Light is readable for all users.  Folks without young eyes might have trouble.  Check out the [intranet demo](https://intranet.fws.gov/region4/demo/article/longleaf-pine-partnership/).

Bold links: b1300c84d4c2148f8b64e53f54749b89902bc790
Body text: 66a4911d4e69098a7b69446468d299b10ed9a01a

Line spacing is determined by vertical rhythm dictated by [typebase](https://devinhunt.github.io/typebase.css/demo/specimen.html).

**Comment by rhewitt22** [comment]
@jenmstrick bumping this issue.  Do you think open sans light is the best choice over open sans regular?

**Comment by jenmstrick** [comment]
Let's make it regular and see. Definitely needs more line spacing for body text, similar to a 1.5 line space in Word.

Decrease font size for all headers. H1 is 4.242rem, so let's try 3. Maybe fonts is something we can sit down and finesse looking at the same screen.

**Comment by rhewitt22** [comment]
Swapped Open Sans light for regular in #27

**Comment by rhewitt22** [comment]
Closing.  If we need to revisit typography we can, but this issue is covering too many things at once, many of which have been addressed.
