### ISSUE TITLE
Complete "Contact Us" nav feature

### ISSUE THREAD

**Issue by jenmstrick** [USFWS/southeast#42]
"Contact Us" should offer users the ability to toggle between two options: submit a form (default) or search the employee directory. If you can build a start on how you think this will work best, that'd be cool.

Also, we may want to see if we can receive info like a phone number or email? Otherwise we have no real way of making this work...

Intro text:
"All inquiries will be submitted to the web manager. Your question or comments and contact information may be forwarded to the correct point of contact within the Southeast Region for a response. Please allow several business days for us to reach you.

If you wish to contact a specific office or employee, you may search our [Employee Directory](url to directory search)."

Form fields:
Name -
Contact Info - (phone number or email address)
Questions or Comments -

**Comment by rhewitt22** [comment]
If all of the requests are coming to me I can just setup an email link.  Even if it's legal (I'm not sure we can collect user data without getting expressed permission from OMB) the only server we have to handle a form submission is ColdFusion, yuck.

**Comment by jenmstrick** [comment]
I used to hard code HTML forms back in the day that get sent to an email. Can you do that? I really want to provide a standard form to make it super easy on the user and easy on you too!

**Comment by rhewitt22** [comment]
The employees name is a link that will open the default email client for the user.  They can provide whatever information they choose.
