### ISSUE TITLE
Create contact feature

### ISSUE THREAD

**Issue by jenmstrick** [USFWS/southeast#5]
I have created spreadsheets with all the contacts I can find by state. Here is one for Arkansas: https://docs.google.com/spreadsheets/d/1hSanXIVMxpuqT02NneRv7hL0KTqPFtcLEv727DnGnxM/edit#gid=0

They are in each state's folder. Should we create one big "Contacts" feature? I broke these out by state so that we can have a few people in the field help us keep this information up-to-date. We could also turn it into one big spreadsheet if that's easier for you.

The idea is to use this info so that anyone can search for a contact, or on a specific page I can say something like, "display contacts from Arkansas at field stations with permits in their title."

Thoughts? Thanks!

**Comment by rhewitt22** [comment]
@jenmstrick I think it makes sense to put this all in one spreadsheet.  We can still pull data out by state/office, but it would be nice to have one place where this is stored.

**Comment by jenmstrick** [comment]
Alright done! Well the spreadsheet isn't done, but I've put it all in one place: https://docs.google.com/spreadsheets/d/1hSanXIVMxpuqT02NneRv7hL0KTqPFtcLEv727DnGnxM/edit

**Comment by jenmstrick** [comment]
Hey! So this info can be used for the "Contact Us" button that's ever-present and sitewide. Again, maybe a filterable list like you did for the social media accounts? Filter by name, keyword, station, state, etc?

**Comment by rhewitt22** [comment]
Closed via #24.

Open a new ticket if you have suggestions for how to better display the contacts list.
