### ISSUE TITLE
Refuges - Find Your Refuge Tool

### ISSUE THREAD

**Issue by jenmstrick** [USFWS/southeast#7]
Copy over the find your refuge tool.

https://docs.google.com/a/doi.gov/document/d/1DvcCjlKT-jrzigRFn_fwNzyINS9f_46UdbP4Sc3HUpc/edit?usp=sharing

**Comment by rhewitt22** [comment]
@jenmstrick I tried to embed the search tool into the page, but since it's coldfusion and redirects the user to a a results page it didn't work.  I'm just linking to the find your hunt page instead.

Closed via fba4d23665ed7e70069792b5ff9a47d789d34e5d
