### ISSUE TITLE
Partners Program - swipe tool and map

### ISSUE THREAD

**Issue by jenmstrick** [USFWS/southeast#9]
Need to bring over the swipe tool & map.

http://www.fws.gov/southeast/es/partners/
to
https://docs.google.com/a/doi.gov/document/d/17d2v7kDc2Lb7IvZIfXq1h7KCy63e8FfUAynRdDMBicI/edit?usp=sharing

**Comment by rhewitt22** [comment]
@jenmstrick do you want me to include any of the supporting text to go along with the swipe tool?  Seems like it doesn't have enough context if it's included by itself.

**Comment by rhewitt22** [comment]
Moved over swipe and map.

Left to go: 2014 accomplishments.

**Comment by jenmstrick** [comment]
You must've added some because what you have looks good to me!

We could make the divider the green color so it stands out more too.

**Comment by rhewitt22** [comment]
@jenmstrick I didn't -- The swipe image kinda comes out of nowhere in the landowner section.  There's no description as to what those images even are.

**Comment by jenmstrick** [comment]
If it's not included in the page then I don't have that info.

**Comment by rhewitt22** [comment]
Closed via 3958d6cd81249bc3388a7115a0a9be0b9012bc04
